git:
  baseurl: {{config_baseurl}}
  prefix: {{config_prefix}}

artifacts-dir: {{builder}}

executor:
  type: qubes
  options:
    dispvm: builder-dvm

+components:
  - {{config_component}}:
      packages: false
      branch: {{config_branch}}
{%- if config_maintainers %}
      maintainers:
{%- for key in config_maintainers %}
        - {{key}}
{%- endfor %}
{% endif %}
